# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangesProjectStatus',
            fields=[
                ('id_changing', models.AutoField(primary_key=True, serialize=False)),
                ('changing_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'changes_project_status',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id_customer', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('invitings_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('changes_project_status_id', models.IntegerField(db_column='Changes_project_status_id')),
                ('projectHistory', models.CharField(blank=True, db_column='ProjectHistory', max_length=80, null=True)),
                ('customerHistory', models.CharField(blank=True, db_column='CustomerHistory', max_length=80, null=True)),
                ('teamHistory', models.CharField(blank=True, db_column='TeamHistory', max_length=80, null=True)),
                ('date', models.DateTimeField(db_column='Date')),
            ],
            options={
                'db_table': 'History',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=256, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('finish_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=256, null=True)),
                ('team_department', models.CharField(blank=True, max_length=256, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=256, null=True)),
                ('developers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.AddField(
            model_name='changesprojectstatus',
            name='id_customer',
            field=models.ForeignKey(blank=True, db_column='id_customer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Lab3App.Customers'),
        ),
        migrations.AddField(
            model_name='changesprojectstatus',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Lab3App.Projects'),
        ),
        migrations.AddField(
            model_name='changesprojectstatus',
            name='id_team',
            field=models.ForeignKey(blank=True, db_column='id_team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Lab3App.Teams'),
        ),
    ]
