# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab3App', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangesProjectStatus',
            fields=[
                ('id_changing', models.AutoField(primary_key=True, serialize=False)),
                ('changing_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'changes_project_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id_customer', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('invitings_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=256, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('finish_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=256, null=True)),
                ('team_department', models.CharField(blank=True, max_length=256, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=256, null=True)),
                ('developers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
    ]
